project:
  type: book

book:
  title: "UBC Smoke Forecast Data Curation"
  author: "NSDF"
  date: "7/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - sys_specs.qmd
    - data_source.qmd
    - data_loading.qmd
bibliography: references.bib

format:
  html:
    code-overflow: wrap
    eval: false
    code-fold: show
  pdf:
    documentclass: scrreprt
    



