project:
  type: book

book:
  title: "UBC Smoke Forecast Data Curation and Distribution"
  author: "Arleth Salinas and Valerio Pascucci \n \n 
  a 'WIRED Global Center' & 'National Science Data Fabric' collaboration"
  date: "Release dat: 7/28/2024"  
  chapters:
    - index.qmd
    - demo.qmd
    - intro.qmd
    - sys_specs.qmd
    - data_source.qmd
    - netcdf_demo.qmd
    - data_loading.qmd
    - data_conversion.qmd
    - data_validation.qmd

bibliography: references.bib

format:
  html:
    code-overflow: wrap
    code-fold: show
    code-annotations: hover
  pdf:
    documentclass: scrreprt